# escape=`
FROM microsoft/nanoserver:latest

LABEL maintainer="Weslei Juan Moser Pereira <wesleimsr@gmail.com>" `
  org.label-schema.name="Drone circleci" `
  org.label-schema.vendor="Weslei Juan Moser Pereira" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-circleci.exe C:/drone-circleci.exe
ENTRYPOINT [ "C:\\drone-circleci.exe" ]